{
  imports = [
    ./bufferline.nix
    ./blink-cmp.nix
    ./competitest.nix
    ./gitsigns.nix
    ./lazygit.nix
    ./lsp-format.nix
    ./lsp.nix
    ./lualine.nix
    ./mini.nix
    ./mini-files.nix
    ./noice.nix
    #./telescope.nix
    ./treesitter.nix
    ./zen-mode.nix
    ./kitty-scrollback.nix
  ];
}
