{ inputs, ... }:

{
  flake-file.inputs = {
    noctalia.url = "github:noctalia-dev/noctalia-shell";
  };

  den.aspects.shells._.noctalia =
    { user, ... }:
    {
      homeManager =
        { config, lib, ... }:
        let
          term = config.home.sessionVariables.TERM;
          noctaliaPluginURL = "https://github.com/noctalia-dev/noctalia-plugins";
          officialPlugins = [
            "battery-actions"
            "clipper"
            "polkit-agent"
            "keybind-cheatsheet"
          ];
          isAutoSpawned = config.programs.niri.autoSpawnShell == "noctalia";
        in
        {
          imports = [
            inputs.noctalia.homeModules.default
          ];

          options.programs.noctalia-shell.userSettings =
            with lib;
            mkOption {
              type = types.attrs;
              example = {
                currentThemeName = "gruvbox";
                showDock = true;
                controlCenterWidgets = [
                  {
                    id = "wifi";
                    enabled = false;
                    width = 100;
                  }
                ];
              };
              default = { };
              description = "User settings to add to default settings, overriding if necessary.";
            };

          config = lib.mkIf isAutoSpawned {

            programs.niri.settings.spawn-at-startup = [
              {
                command = [ "noctalia-shell" ];
              }
            ];

            programs.noctalia-shell = {
              enable = true;
              plugins = {
                sources = [
                  {
                    enabled = true;
                    name = "Official Noctalia Plugins";
                    url = noctaliaPluginURL;
                  }
                ];

                states = lib.genAttrs officialPlugins (_: {
                  enabled = true;
                  sourceUrl = noctaliaPluginURL;
                });

                version = 2;
              };

              pluginSettings = {
                clipper.fullscreenMode = true;
              };

              # File can easily be generated by editing graphically in settings and
              # then selecting option "Copy settings" from "General" tab and in my
              # opinion most settings can be derived from there whereas only a few
              # where variables may come handy should abuse nix
              settings = lib.recursiveUpdate (lib.recursiveUpdate
                (builtins.fromJSON (builtins.readFile ./settings.json))
                {
                  general = {
                    # Should be easily identifyable in user section
                    avatarImage = "${config.home.sessionVariables.NH_FLAKE}/nix-config/modules/users/${user.userName}/.face";
                  };

                  ui = {
                    fontDefault = "Mona Sans Display Light";
                    fontFixed = "VictorMono NF";
                  };

                  appLauncher = {
                    terminalCommand = "${term} -e";
                  };

                  colorSchemes = {
                    predefinedScheme = "Gruvbox";
                  };
                }
                # Users setting potentially override other two attrsets
              ) (config.programs.noctalia-shell.userSettings);
            };
          };
        };
    };
}
