when:
  - event: push
    branch: main

steps:
  - name: flake-check
    image: nixos/nix:latest
    commands:
      - |
        tee -a /etc/nix/nix.conf <<'EOF'
        experimental-features = nix-command flakes
        accept-flake-config = true
        EOF
      - nix run .#write-flake --show-trace
      - nix flake check -L

  - name: setup-nix-and-cache
    image: nixos/nix:latest
    commands: 
      - |
        tee -a /etc/nix/nix.conf <<'EOF'
        experimental-features = nix-command flakes
        accept-flake-config = true
        EOF
      - nix profile add nixpkgs#cachix
      # posix-compliant list
      - |
        for cache in \
          amanako \
          nix-community \
          yazi \
          niri \
          noctalia \
          helix \
          nix-gaming \
          vic \
          fzakaria
        do
          cachix use "$cache"
        done
      - |
        tee -a /etc/nix/nix.conf <<'EOF'
        substituters = https://attic.xuyh0120.win/lantian
        trusted-public-keys = lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc=
        EOF

  - name: build-flake
    image: nixos/nix:latest
    commands: 
      - |
        tee -a /etc/nix/nix.conf <<'EOF'
        experimental-features = nix-command flakes
        accept-flake-config = true
        EOF
      - nix run .#write-flake --show-trace
      - set -xeuo pipefail
      - nix run github:juspay/omnix#default -- ci run --results=om.json

  - name: push-to-cache
    image: nixos/nix:latest
    environment:
      CACHIX_AUTH_TOKEN: ${CACHIX_AUTH_TOKEN}
    commands: 
      - |
        tee -a /etc/nix/nix.conf <<'EOF'
        experimental-features = nix-command flakes
        accept-flake-config = true
        EOF
      - nix run github:juspay/cachix-push -- \
          --cache amanako \
          --subflake ROOT \
          --prefix "$(git rev-parse --abbrev-ref HEAD)" < om.json
