when:
  event: push
  branch: main

steps:
  - name: flake-check
    image: nixos/nix:unstable
    commands:
      - . $HOME/.nix-profile/etc/profile.d/nix.sh
      - nix run .#write-flake --show-trace
      - nix flake check -L

  - name: flake-lint
    image: ghcr.io/determinate-systems/flake-checker:latest
    commands:
      - flake-checker .

  - name: setup-nix-and-cache
    image: nixos/nix:unstable
    environment:
      CACHIX_AUTH_TOKEN: ${CACHIX_AUTH_TOKEN}
    commands:
      - curl -L https://nixos.org/nix/install | bash
      - . $HOME/.nix-profile/etc/profile.d/nix.sh
      - nix --version
      - |
        sudo mkdir -p /etc/nix
        echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
      - nix profile install github:cachix/cachix/v17
      - cachix use amanako
      - |
        sudo tee -a /etc/nix/nix.conf <<'EOF'
        substituters = https://attic.xuyh0120.win/lantian
        trusted-public-keys = lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc=
        EOF

  - name: build-flake
    image: nixos/nix:unstable
    commands:
      - . $HOME/.nix-profile/etc/profile.d/nix.sh
      - set -xeuo pipefail
      - nix run .#write-flake --show-trace
      - nix --accept-flake-config run github:juspay/omnix#default -- ci run --results=om.json

  - name: push-to-cache
    image: nixos/nix:unstable
    environment:
      CACHIX_AUTH_TOKEN: ${CACHIX_AUTH_TOKEN}
    commands:
      - . $HOME/.nix-profile/etc/profile.d/nix.sh
      - nix run github:juspay/cachix-push -- \
          --cache amanako \
          --subflake ROOT \
          --prefix "$(git rev-parse --abbrev-ref HEAD)" < om.json
