when:
  - event: cron
    cron: "bump flake" # Runs Sunday 03:40 UTC
  - event: manual

steps:
  - name: update-and-check-flake
    image: nixos/nix:latest
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - |
        export NIX_CONFIG=$(cat <<-EOF
        extra-experimental-features = nix-command flakes
        access-tokens = github.com=$${GITHUB_TOKEN}
        EOF
        )
      - nix profile install nixpkgs#just
      - just fupdate
      - nix --accept-flake-config flake check -L

  - name: commit-and-push
    image: alpine/git:latest
    environment:
      GIT_AUTHOR_NAME:
        from_secret: GIT_AUTHOR_NAME
      GIT_AUTHOR_EMAIL:
        from_secret: GIT_AUTHOR_EMAIL
      GITEA_TOKEN:
        from_secret: GITEA_TOKEN
      GIT_SSH_PRIVATE_KEY:
        from_secret: GIT_SSH_PRIVATE_KEY
      GIT_SSH_PUBLIC_KEY:
        from_secret: GIT_SSH_PUBLIC_KEY
    commands:
      - |
        git config --global user.name "$${GIT_AUTHOR_NAME}"
        git config --global user.email "$${GIT_AUTHOR_EMAIL}"
        git config --global gpg.format ssh
        git config --global commit.gpgsign true

      - |
        mkdir -p ~/.ssh
        echo "$${GIT_SSH_PRIVATE_KEY}" > ~/.ssh/signing_key
        echo "$${GIT_SSH_PUBLIC_KEY}" > ~/.ssh/signing_key.pub
        chmod 600 ~/.ssh/signing_key

      - |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/signing_key

      - |
        git config --global user.signingkey "$(cat ~/.ssh/signing_key.pub)"
        git config --global gpg.ssh.allowedSignersFile ~/.ssh/allowed_signers
        echo "$(git config --global user.email) namespaces=\"git\" $(cat ~/.ssh/signing_key.pub)" > ~/.ssh/allowed_signers

      - |
        BRANCH="weekly-flake-update"
        git checkout -b $BRANCH
        git add flake.lock

      - |
        if git diff --cached --quiet; then
          echo "flake.lock unchanged – nothing to do."
          exit 0
        fi

      - |
        git commit -S -m "Weekly flake.lock update"
        git push https://x-access-token:$${GITEA_TOKEN}@codeberg.org/${CI_REPO}.git "$BRANCH"

  - name: open-pr
    image: woodpeckercommunity/gitea-pull-request-create-plugin:latest
    pull: true
    settings:
      gitea_address: https://codeberg.org
      gitea_token:
        from_secret: GITEA_TOKEN
      owner: ${CI_REPO_OWNER}
      repo: ${CI_REPO_NAME}
      branch: weekly-flake-update
      base_branch: dev
      pr_title: Bump flake
      pr_body: |
        Update flake.lock dependencies.
        PR automatically created by Woodpecker CI.
      skip_on_missing_branch: true
      skip_on_empty_branch: true
      close_pr_if_empty: true
      delete_branch_if_pr_empty: true
      merge_when_checks_succeed: true
      delete_branch_after_merge: true
