when:
  - event: push
    branch: [main, dev]

steps:
  - name: check flake
    image: nixos/nix:latest
    commands:
      - |
        export NIX_CONFIG=$(cat <<-EOF
        extra-experimental-features = nix-command flakes
        accept-flake-config = true
        EOF
        )
      - nix flake check -L
