when:
  - event: push
    branch: main

steps:
  - name: format-nix-alejandra
    image: alpine:3.20
    commands:
      - apk add --no-cache alejandra
      - alejandra -c **/*.nix

  - name: format-markdown-mdformat
    image: alpine:3.20
    commands:
      - apk add --no-cache py3-pip
      - pip install mdformat
      - mdformat -c **/*.md

  - name: format-lua-stylua
    image: alpine:3.20
    commands:
      - apk add --no-cache stylua
      - stylua -c **/*.lua
