name: Test build

on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

env:
  CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Pull cachix
        run: nix profile add nixpkgs#cachix

      - name: Setup caches ( cachix + extra substituters )
        run: |
          CACHES=(
            amanako
            nix-community
            yazi
            niri
            noctalia
            helix
          )
          for cache in "${CACHES[@]}"; do
            cachix use "$cache"
          done

          echo "substituters = https://cache.nixos.org https://attic.xuyh0120.win/lantian" \
            | sudo tee -a /etc/nix/nix.conf

          echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc=" \
            | sudo tee -a /etc/nix/nix.conf

      - name: Lint flake
        uses: DeterminateSystems/flake-checker-action@main

      - name: Build flake
        run: nix --accept-flake-config run github:juspay/omnix#default -- ci run --results=om.json

      - name: Push to cache
        run: nix run github:juspay/cachix-push -- --cache amanako --subflake ROOT --prefix "$(git branch --show-current)" < om.json
