---
name: Test build

on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
env:
  CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          # Remove tools which take up most space quickly
          android: true
          haskell: true
          dotnet: true
          large-packages: false
          tool-cache: false
          docker-images: false
          swap-storage: false

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: experimental-features = nix-command flakes

      - name: Setup caches
        uses: cachix/cachix-action@v17
        with:
          name: amanako
          skipPush: true
          extraPullNames: nix-community, yazi, niri, noctalia, helix, statix, nix-gaming

      - name: Setup additional substituters
        run: |
          echo "substituters = https://attic.xuyh0120.win/lantian https://cache.nixos.asia/oss" | sudo tee -a /etc/nix/nix.conf
          echo "trusted-public-keys = lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc= oss:KO872wNJkCDgmGN3xy9dT89WAhvv13EiKncTtHDItVU=" | sudo tee -a /etc/nix/nix.conf

      - name: Check flake
        run: nix --accept-flake-config flake check -L

      - name: Lint flake
        uses: DeterminateSystems/flake-checker-action@v12

      - name: Build flake
        run: |
          set -xeuo pipefail
          nix --accept-flake-config run github:juspay/omnix#default -- ci run --results=om.json

      - name: Push to cache
        run: |
          nix run github:juspay/cachix-push -- --cache amanako \
            --subflake ROOT --prefix "$(git branch --show-current)" < om.json
