name: "Test"

env:
  CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Enable nix-command & flakes
        run: |
          echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
          export NIX_CONFIG="experimental-features = nix-command flakes"
          nix --version
          nix profile list

      - name: Install Needed Packages
        run: |
          nix-env -iA nixpkgs.cachix
          nix-env -iA github:juspay/omnix
          nix-env -iA github:juspay/cachix-push

      - name: Flake check
        run: nix flake check -L
        timeout-minutes: 30

      - name: Setup Cachix
        run: |
          CACHES=(
            'amanako'
            'nix-community'
            'yazi'
            'niri'
            'noctalia'
            'nix'
          )
          for cache in ${CACHES[@]}; do
            cachix use $cache
          done
      - name: Build output
        run: om ci run --results=/om.json
      - name: Push to cache
        run: cachix-push-om-outputs -c amanako --subflake ROOT --prefix "$(git rev-parse --short HEAD)" < /om.json
